const AvatarImage = [
    require('./Avatar/avatar1.png'),
    require('./Avatar/avatar2.png'),
    require('./Avatar/avatar3.png'),
    require('./Avatar/avatar4.png'),
    require('./Avatar/avatar5.png'),
    require('./Avatar/avatar6.png'),
    require('./Avatar/avatar7.png'),
    require('./Avatar/avatar8.png'),
    require('./Avatar/avatar9.png'),
    require('./Avatar/avatar10.png'),
    require('./Avatar/avatar11.png'),
    require('./Avatar/avatar12.png'),
    require('./Avatar/avatar13.png'),
    require('./Avatar/avatar14.png'),
    require('./Avatar/avatar15.png'),
    require('./Avatar/avatar16.png'),
    require('./Avatar/avatar17.png'),
    require('./Avatar/avatar18.png'),
    require('./Avatar/avatar19.png'),
    require('./Avatar/avatar20.png'),
    require('./Avatar/avatar21.png'),
    require('./Avatar/avatar22.png'),
    require('./Avatar/avatar23.png'),
    require('./Avatar/avatar24.png'),
    require('./Avatar/avatar25.png'),
    require('./Avatar/avatar26.png'),
    require('./Avatar/avatar27.png'),
    require('./Avatar/avatar28.png'),
    require('./Avatar/avatar29.png'),
    require('./Avatar/avatar30.png')
]

export default AvatarImage;